// packages/vue/src/components/color-swatch.vue
<script setup lang="ts">
import type { AriaAttributes } from 'vue'
import { useHueyContext } from '@composables/use-huey-context'
import { hueyColor } from '@hueycolor/core'
import { computed } from 'vue'

defineProps<ColorSwatchProps>()

const { setColor, colorValue } = useHueyContext()

function chooseColor(e: Event, color: string) {
  e.preventDefault()

  setColor(color)
}

const selectedColor = computed(() => {
  return colorValue.value.toHexString()
})

function isSelected(color: string) {
  const compareToColor = hueyColor(color).toHexString()

  return selectedColor.value === compareToColor
}
</script>

<script lang="ts">
export interface ColorSwatchProps extends /* @vue-ignore */ AriaAttributes {
  swatch: Array<string>
}
</script>

<template>
  <div v-if="swatch" role="listbox" :aria-label="$props['aria-label'] ?? 'Color swatch'" huey-swatch>
    <div
      v-for="color in swatch"
      :key="color"
      tabindex="0"
      role="option"
      :aria-label="color"
      huey-swatch-color
      :aria-selected="isSelected(color)"
      :style="{ '--swatch-color': color }"
      @click="chooseColor($event, color)"
      @keydown.enter.space.prevent="chooseColor($event, color)"
    />
  </div>
</template>

<style>
[huey-swatch] {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
  flex-wrap: wrap;
}
[huey-swatch-color] {
  --huey-swatch-color-size: 16px;

  cursor: pointer;
  width: var(--huey-swatch-color-size);
  height: var(--huey-swatch-color-size);
  background-color: var(--swatch-color);
  border-radius: 4px;
}
</style>

// packages/svelte/src/components/color-swatch.svelte
<script lang="ts" module>
  export interface ColorSwatchProps {
    swatch: Array<string>
    'aria-label'?: string
  }
</script>

<script lang="ts">
  import { hueyColor } from '@hueycolor/core'
  import { useHueyContext } from '../context/huey-context.svelte'

  let { swatch, 'aria-label': ariaLabel }: ColorSwatchProps = $props()

  const ctx = useHueyContext()

  function chooseColor(e: Event, color: string) {
    e.preventDefault()
    ctx.setColor(color)
  }

  const selectedColor = $derived(ctx.colorValue.toHexString())

  function isSelected(color: string) {
    const compareToColor = hueyColor(color).toHexString()
    return selectedColor === compareToColor
  }

  function onKeydown(e: KeyboardEvent, color: string) {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      chooseColor(e, color)
    }
  }

  const swatchMarker: Record<string, string> = { 'huey-swatch': '' }
  const swatchColorMarker: Record<string, string> = { 'huey-swatch-color': '' }
</script>

{#if swatch}
  <div {...swatchMarker} role="listbox" aria-label={ariaLabel ?? 'Color swatch'}>
    {#each swatch as color (color)}
      <div
        {...swatchColorMarker}
        tabindex="0"
        role="option"
        aria-label={color}
        aria-selected={isSelected(color)}
        style={`--swatch-color: ${color};`}
        onclick={e => chooseColor(e, color)}
        onkeydown={e => onKeydown(e, color)}
      ></div>
    {/each}
  </div>
{/if}

<style>
  :global {
    [huey-swatch] {
      display: flex;
      align-items: center;
      justify-content: center;
      gap: 8px;
      flex-wrap: wrap;
    }

    [huey-swatch-color] {
      --huey-swatch-color-size: 16px;
      --huey-swatch-color-radius: 4px;

      cursor: pointer;
      width: var(--huey-swatch-color-size);
      height: var(--huey-swatch-color-size);
      background-color: var(--swatch-color);
      border-radius: var(--huey-swatch-color-radius);
    }
  }
</style>
