// packages/svelte/src/components/alpha-input.svelte
<script lang="ts" module>
  import type { HTMLInputAttributes } from 'svelte/elements'

  export interface AlphaInputProps extends HTMLInputAttributes {}
</script>

<script lang="ts">
  import type { ArrowDirection } from '@hueycolor/core'
  import { getChannelBounds } from '@hueycolor/core'
  import { useHueyContext } from '../context/huey-context.svelte'
  import ChannelInput from './internal/channel-input.svelte'

  let { ...rest }: AlphaInputProps = $props()

  const { min, max } = getChannelBounds('a')
  const ctx = useHueyContext()

  let alphaRef = $state((ctx.alpha * 100).toFixed(0))

  $effect(() => {
    const rounded = (ctx.alpha * 100).toFixed(0)
    if (alphaRef !== rounded) {
      alphaRef = rounded
    }
  })

  function updateValue(input: HTMLInputElement, value: number) {
    input.value = String(value)
    alphaRef = input.value
    ctx.alpha = value / 100
  }

  function handleEnter(e: KeyboardEvent) {
    const input = e.target as HTMLInputElement
    const value = Number(input.value)

    if (Number.isNaN(value) || value < min || value > max) {
      input.value = alphaRef
      return
    }

    updateValue(input, value)
  }

  function bumpValue(e: KeyboardEvent, direction: Exclude<ArrowDirection, 'left' | 'right'>) {
    const input = e.target as HTMLInputElement
    const current = Number(input.value)

    let step = e.shiftKey ? 10 : 1
    step *= direction === 'down' ? -1 : 1

    const base = Number.isNaN(current) ? Number(alphaRef) : current
    const value = Math.min(max, Math.max(min, base + step))

    updateValue(input, value)
  }

  function handleKeydown(e: KeyboardEvent) {
    switch (e.key) {
      case 'Enter':
        e.preventDefault()
        handleEnter(e)
        break
      case 'ArrowUp':
        e.preventDefault()
        bumpValue(e, 'up')
        break
      case 'ArrowDown':
        e.preventDefault()
        bumpValue(e, 'down')
        break
    }
  }

  const marker: Record<string, string> = { 'huey-input': 'alpha' }
</script>

<ChannelInput
  {...rest}
  {...marker}
  value={alphaRef}
  onkeydown={handleKeydown}
/>

// packages/vue/src/components/alpha-input.vue
<script setup lang="ts">
import type { ArrowDirection } from '@hueycolor/core'
import type { InputHTMLAttributes } from 'vue'
import ChannelInput from '@components/internal/channel-input.vue'
import { useHueyContext } from '@composables/use-huey-context'
import { getChannelBounds } from '@hueycolor/core'
import { ref, watch } from 'vue'

defineProps<AlphaInputProps>()

const { min, max } = getChannelBounds('a')

const { alpha } = useHueyContext()

const alphaRef = ref((alpha.value * 100).toFixed(0))

watch(alpha, (newAlpha) => {
  const rounded = (newAlpha * 100).toFixed(0)

  if (alphaRef.value !== rounded) {
    alphaRef.value = rounded
  }
})

function updateValue(input: HTMLInputElement, value: number) {
  input.value = String(value)
  alphaRef.value = input.value
  alpha.value = value / 100
}

function handleEnter(e: KeyboardEvent) {
  const input = e.target as HTMLInputElement
  const value = Number(input.value)

  if (Number.isNaN(value) || value < min || value > max) {
    input.value = alphaRef.value

    return
  }

  updateValue(input, value)
}

function bumpValue(e: KeyboardEvent, direction: Exclude<ArrowDirection, 'left' | 'right'>) {
  const input = e.target as HTMLInputElement
  const current = Number(input.value)

  let step = e.shiftKey ? 10 : 1
  step *= direction === 'down' ? -1 : 1

  const base = Number.isNaN(current) ? Number(alphaRef.value) : current
  const value = Math.min(max, Math.max(min, base + step))

  updateValue(input, value)
}
</script>

<script lang="ts">
export interface AlphaInputProps extends /* @vue-ignore */ InputHTMLAttributes {}
</script>

<template>
  <ChannelInput
    :value="alphaRef"
    @keydown.prevent.enter="handleEnter"
    @keydown.prevent.up="bumpValue($event, 'up')"
    @keydown.prevent.down="bumpValue($event, 'down')"
  />
</template>
