// packages/svelte/src/components/blue-input.svelte
<script lang="ts" module>
  import type { HTMLInputAttributes } from 'svelte/elements'

  export interface BlueInputProps extends HTMLInputAttributes {}
</script>

<script lang="ts">
  import type { ArrowDirection } from '@hueycolor/core'
  import { getChannelBounds, hslToRgb, rgbToHsl } from '@hueycolor/core'
  import { useHueyContext } from '../context/huey-context.svelte'
  import ChannelInput from './internal/channel-input.svelte'

  let { ...rest }: BlueInputProps = $props()

  const { min, max } = getChannelBounds('b')
  const ctx = useHueyContext()

  const { b: initialB } = ctx.colorValue.toRgb()
  let blueRef = $state(initialB.toFixed(0))

  $effect(() => {
    const { b } = hslToRgb(ctx.hue, ctx.saturation, ctx.lightness)
    const rounded = b.toFixed(0)
    if (blueRef !== rounded) {
      blueRef = rounded
    }
  })

  function updateValue(input: HTMLInputElement, value: number) {
    input.value = String(value)
    blueRef = input.value

    const { r, g } = ctx.colorValue.toRgb()
    const { h, s, l } = rgbToHsl(r, g, value)
    ctx.hue = h
    ctx.saturation = s
    ctx.lightness = l
  }

  function handleEnter(e: KeyboardEvent | FocusEvent) {
    const input = e.target as HTMLInputElement
    const value = Number(input.value)

    if (Number.isNaN(value) || value < min || value > max) {
      input.value = blueRef
      return
    }

    updateValue(input, value)
  }

  function bumpValue(e: KeyboardEvent, direction: Exclude<ArrowDirection, 'left' | 'right'>) {
    const input = e.target as HTMLInputElement
    const current = Number(input.value)

    let step = e.shiftKey ? 10 : 1
    step *= direction === 'down' ? -1 : 1

    const base = Number.isNaN(current) ? Number(blueRef) : current
    const value = Math.min(max, Math.max(min, base + step))

    updateValue(input, value)
  }

  function handleKeydown(e: KeyboardEvent) {
    switch (e.key) {
      case 'Enter':
        e.preventDefault()
        handleEnter(e)
        break
      case 'ArrowUp':
        e.preventDefault()
        bumpValue(e, 'up')
        break
      case 'ArrowDown':
        e.preventDefault()
        bumpValue(e, 'down')
        break
    }
  }

  const marker: Record<string, string> = { 'huey-input': 'blue' }
</script>

<ChannelInput
  {...rest}
  {...marker}
  value={blueRef}
  onkeydown={handleKeydown}
  onblur={handleEnter}
/>

// packages/vue/src/components/blue-input.vue
<script setup lang="ts">
import type { ArrowDirection } from '@hueycolor/core'
import type { InputHTMLAttributes } from 'vue'
import ChannelInput from '@components/internal/channel-input.vue'
import { useHueyContext } from '@composables/use-huey-context'
import { getChannelBounds, hslToRgb, rgbToHsl } from '@hueycolor/core'
import { ref, watch } from 'vue'

defineProps<BlueInputProps>()

const { min, max } = getChannelBounds('g')

const { hue, saturation, lightness, colorValue } = useHueyContext()

const { b } = colorValue.value.toRgb()
const blueRef = ref(b.toFixed(0))

watch([hue, saturation, lightness], ([newHue, newSaturation, newLightness]) => {
  const { b } = hslToRgb(newHue, newSaturation, newLightness)
  const rounded = b.toFixed(0)

  if (blueRef.value !== rounded) {
    blueRef.value = rounded
  }
})

function updateValue(input: HTMLInputElement, value: number) {
  input.value = String(value)
  blueRef.value = input.value

  const { r, g } = colorValue.value.toRgb()
  const { h, s, l } = rgbToHsl(r, g, value)
  hue.value = h
  saturation.value = s
  lightness.value = l
}

function handleEnter(e: KeyboardEvent | FocusEvent) {
  const input = e.target as HTMLInputElement
  const value = Number(input.value)

  if (Number.isNaN(value) || value < min || value > max) {
    input.value = blueRef.value

    return
  }

  updateValue(input, value)
}

function bumpValue(e: KeyboardEvent, direction: Exclude<ArrowDirection, 'left' | 'right'>) {
  const input = e.target as HTMLInputElement
  const current = Number(input.value)

  let step = e.shiftKey ? 10 : 1
  step *= direction === 'down' ? -1 : 1

  const base = Number.isNaN(current) ? Number(blueRef.value) : current
  const value = Math.min(max, Math.max(min, base + step))

  updateValue(input, value)
}
</script>

<script lang="ts">
export interface BlueInputProps extends /* @vue-ignore */ InputHTMLAttributes {}
</script>

<template>
  <ChannelInput
    :value="blueRef"
    huey-input="blue"
    @keydown.prevent.enter="handleEnter"
    @keydown.prevent.up="bumpValue($event, 'up')"
    @keydown.prevent.down="bumpValue($event, 'down')"
    @blur="handleEnter"
  />
</template>
