// packages/svelte/src/components/color-dropper.svelte
<script lang="ts" module>
  import type { Snippet } from 'svelte'

  export interface ColorDropperProps {
    'aria-label'?: string
    class?: string
    onerror?: (error: Error) => void
    children?: Snippet
  }
</script>

<script lang="ts">
  import { clamp, hueyColor } from '@hueycolor/core'
  import { useHueyContext } from '../context/huey-context.svelte'

  let { 'aria-label': ariaLabel, class: className, onerror, children }: ColorDropperProps = $props()

  const ctx = useHueyContext()

  const dropper = typeof window !== 'undefined' && (window as any).EyeDropper
    ? new (window as any).EyeDropper()
    : undefined

  function sip() {
    if (!dropper)
      return

    dropper.open().then((result: { sRGBHex: string }) => {
      const newColor = hueyColor(result.sRGBHex)
      const { h, s, l } = newColor.toHsl()

      ctx.hue = clamp(h, 0, 360)
      ctx.saturation = clamp(s, 0, 100)
      ctx.lightness = clamp(l, 0, 100)
    }).catch((e: Error) => {
      onerror?.(e)
    })
  }

  const dropperMarker: Record<string, string> = { 'huey-color-dropper': '' }
</script>

{#if dropper}
  <button
    {...dropperMarker}
    class={className}
    aria-label={ariaLabel ?? 'Eye dropper button'}
    onclick={sip}
  >
    {@render children?.()}
  </button>
{/if}

<style>
  :global {
    [huey-color-dropper] {
      cursor: pointer;
      width: fit-content;
      display: flex;
      align-items: center;
      justify-content: center;
    }
  }
</style>

// packages/vue/src/components/color-dropper.vue
<script setup lang="ts">
import type { ButtonHTMLAttributes } from 'vue'
import { useHueyContext } from '@composables/use-huey-context'
import { clamp, hueyColor } from '@hueycolor/core'
import { ref } from 'vue'

const props = defineProps<ColorDropperProps>()
const emit = defineEmits<ColorDropperEmits>()

const { hue, saturation, lightness } = useHueyContext()

const dropper = ref()

// @ts-expect-error TS unaware of EyeDropper: https://developer.mozilla.org/en-US/docs/Web/API/EyeDropper#browser_compatibility
if (window.EyeDropper) {
  // @ts-expect-error EyeDropper is guaranteed
  dropper.value = new EyeDropper()
}

function sip() {
  if (!dropper.value) {
    return
  }

  dropper.value.open().then((result: any) => {
    const newColor = hueyColor(result.sRGBHex)
    const { h, s, l } = newColor.toHsl()

    hue.value = clamp(h, 0, 360)
    saturation.value = clamp(s, 0, 100)
    lightness.value = clamp(l, 0, 100)
  }).catch((e: Error) => { emit('error', e) })
}
</script>

<script lang="ts">
interface ColorDropperProps extends /* @vue-ignore */ ButtonHTMLAttributes {}

interface ColorDropperEmits {
  error: [error: Error]
}
</script>

<template>
  <button v-if="dropper" huey-color-dropper v-bind="{ ...props }" :aria-label="$props['aria-label'] ?? 'Eye dropper button'" @click="sip">
    <slot />
  </button>
</template>

<style>
[huey-color-dropper] {
  cursor: pointer;
  width: fit-content;
  display: flex;
  align-items: center;
  justify-content: center;
}
</style>
