// packages/svelte/src/components/hue-slider.svelte
<script lang="ts" module>
  import type { ColorSliderProps } from './internal/channel-slider.svelte'

  export interface HueSliderProps extends Omit<ColorSliderProps, 'value'> {}
</script>

<script lang="ts">
  import { useHueyContext } from '../context/huey-context.svelte'
  import ChannelSlider from './internal/channel-slider.svelte'

  let { 'aria-label': ariaLabel, ...rest }: HueSliderProps = $props()

  const ctx = useHueyContext()

  const thumbBg = $derived(`hsl(${ctx.hue}, 100%, 50%)`)

  const marker: Record<string, string> = { 'huey-slider': 'hue' }
</script>

<ChannelSlider
  {...rest}
  {...marker}
  bind:value={ctx.hue}
  aria-label={ariaLabel ?? 'Hue slider'}
  max={360}
  min={0}
  step={1}
  style={`--huey-thumb-color: ${thumbBg};`}
/>

// packages/vue/src/components/hue-slider.vue
<script setup lang="ts">
import type { ColorSliderProps } from '@components/internal/channel-slider.vue'
import ChannelSlider from '@components/internal/channel-slider.vue'
import { useHueyContext } from '@composables/use-huey-context'
import { computed } from 'vue'

defineProps<HueSliderProps>()

const { hue } = useHueyContext()

const thumbBg = computed(() => {
  return `hsl(${hue.value}, 100%, 50%)`
})
</script>

<script lang="ts">
export interface HueSliderProps extends /* @vue-ignore */ ColorSliderProps {}
</script>

<template>
  <ChannelSlider
    v-bind="{ ...$props }"
    v-model="hue"
    :aria-label="$props['aria-label'] ?? 'Hue slider'"
    huey-slider
    :max="360"
    :min="0"
    :step="1"
    :style="{
      'background': 'linear-gradient(to right, #f00 0%, #ff0 17%, #0f0 33%, #0ff 50%, #00f 67%, #f0f 83%, #f00 100%)',
      '--huey-thumb-color': thumbBg,
    }"
  />
</template>

<style>

</style>
