// packages/svelte/src/components/lightness-slider.svelte
<script lang="ts" module>
  import type { ColorSliderProps } from './internal/channel-slider.svelte'

  export interface LightnessSliderProps extends Omit<ColorSliderProps, 'value'> {}
</script>

<script lang="ts">
  import { useHueyContext } from '../context/huey-context.svelte'
  import ChannelSlider from './internal/channel-slider.svelte'

  let { 'aria-label': ariaLabel, orientation, ...rest }: LightnessSliderProps = $props()

  const ctx = useHueyContext()

  const thumbBg = $derived(`hsl(${ctx.hue}, ${ctx.saturation}%, ${ctx.lightness}%)`)

  const trackBg = $derived.by(() => {
    const dir = orientation === 'vertical' ? 'to top' : 'to right'
    return `linear-gradient(${dir}, #000, hsl(${ctx.hue}, ${ctx.saturation}%, 50%), #fff)`
  })

  const marker: Record<string, string> = { 'huey-slider': 'lightness' }
</script>

<ChannelSlider
  {...rest}
  {...marker}
  {orientation}
  bind:value={ctx.lightness}
  aria-label={ariaLabel ?? 'Lightness slider'}
  max={100}
  min={0}
  step={1}
  style={`background: ${trackBg}; --huey-thumb-color: ${thumbBg};`}
/>

// packages/vue/src/components/lightness-slider.vue
<script setup lang="ts">
import type { ColorSliderProps } from '@components/internal/channel-slider.vue'
import ChannelSlider from '@components/internal/channel-slider.vue'
import { useHueyContext } from '@composables/use-huey-context'
import { computed, useAttrs } from 'vue'

defineProps<LightnessSliderProps>()

const attrs = useAttrs()
const { hue, saturation, lightness } = useHueyContext()

const thumbBg = computed(() => {
  return `hsl(${hue.value}, ${saturation.value}%, ${lightness.value}%)`
})

const trackBg = computed(() => {
  const dir = attrs.orientation === 'vertical' ? 'to top' : 'to right'

  return `linear-gradient(${dir}, #000, hsl(${hue.value}, ${saturation.value}%, 50%), #fff)`
})
</script>

<script lang="ts">
export interface LightnessSliderProps extends /* @vue-ignore */ ColorSliderProps {}
</script>

<template>
  <ChannelSlider
    v-bind="{ ...$props }"
    v-model="lightness"
    :aria-label="$props['aria-label'] ?? 'Lightness slider'"
    huey-slider="lightness"
    :max="100"
    :min="0"
    :step="1"
    :style="{
      'background': trackBg,
      '--huey-thumb-color': thumbBg,
    }"
  />
</template>

<style>

</style>
