// packages/svelte/src/components/saturation-slider.svelte
<script lang="ts" module>
  import type { ColorSliderProps } from './internal/channel-slider.svelte'

  export interface SaturationSliderProps extends Omit<ColorSliderProps, 'value'> {}
</script>

<script lang="ts">
  import { useHueyContext } from '../context/huey-context.svelte'
  import ChannelSlider from './internal/channel-slider.svelte'

  let { 'aria-label': ariaLabel, orientation, ...rest }: SaturationSliderProps = $props()

  const ctx = useHueyContext()

  const thumbBg = $derived(`hsl(${ctx.hue}, ${ctx.saturation}%, 50%)`)

  const trackBg = $derived.by(() => {
    const dir = orientation === 'vertical' ? 'to top' : 'to right'
    return `linear-gradient(${dir}, hsl(${ctx.hue}, 0%, 50%), hsl(${ctx.hue}, 100%, 50%))`
  })

  const marker: Record<string, string> = { 'huey-slider': 'saturation' }
</script>

<ChannelSlider
  {...rest}
  {...marker}
  {orientation}
  bind:value={ctx.saturation}
  aria-label={ariaLabel ?? 'Saturation slider'}
  max={100}
  min={0}
  step={1}
  style={`background: ${trackBg}; --huey-thumb-color: ${thumbBg};`}
/>

// packages/vue/src/components/saturation-slider.vue
<script setup lang="ts">
import type { ColorSliderProps } from '@components/internal/channel-slider.vue'
import ChannelSlider from '@components/internal/channel-slider.vue'
import { useHueyContext } from '@composables/use-huey-context'
import { computed, useAttrs } from 'vue'

defineProps<SaturationSliderProps>()

const attrs = useAttrs()
const { hue, saturation } = useHueyContext()

const thumbBg = computed(() => {
  return `hsl(${hue.value}, ${saturation.value}%, 50%)`
})

const trackBg = computed(() => {
  const dir = attrs.orientation === 'vertical' ? 'to top' : 'to right'
  return `linear-gradient(${dir}, hsl(${hue.value}, 0%, 50%), hsl(${hue.value}, 100%, 50%))`
})
</script>

<script lang="ts">
export interface SaturationSliderProps extends /* @vue-ignore */ ColorSliderProps {}
</script>

<template>
  <ChannelSlider
    v-bind="{ ...$props }"
    v-model="saturation"
    :aria-label="$props['aria-label'] ?? 'Saturation slider'"
    huey-slider="saturation"
    :max="100"
    :min="0"
    :step="1"
    :style="{
      'background': trackBg,
      '--huey-thumb-color': thumbBg,
    }"
  />
</template>

<style>

</style>
